import 'package:flutter/material.dart';

class AppColors {
  static const Color selectedColor = Color(0xFFEEF2F6);
  static const Color blackSupplementary = Color(0xFF273240);
  static const Color activeText = Color(0xFF1D1B20);
  static const Color navbarInactiveText = Color(0xFF49454F);
  static const Color primaryColor = Color(0xFF1B609D);
  static const Color skyeBlue = Color(0xFF0CA5DA);
  static const Color lightBlue = Color(0xFF157FB9);
  static const Color deepBlue = Color(0xFF273240);
  static const Color royalBlue = Color(0xFF091B3D);
  static const Color blackText = Color(0xFF1C1C1C);
  static const Color deepBrown = Color(0xFF272728);
  static const Color blackShade400 = Color(0xFF0F0F0F);
  static const Color blackShade50 = Color(0xFF676767);
  static const Color lightBorder = Color(0xFFE9EAF4);
  static const Color black = Color(0xFF000000);
  static const Color deepAsh = Color(0xFF575758);
  static const Color lightAsh = Color(0xFFF7F9FB);
  static const Color red = Color(0xFFF31E45);
  static const Color redShade500 = Color(0xFFEC5252);
  static const Color redShade50 = Color(0xFFFFEEF1);
  static const Color redShade200 = Color(0xFFFFF4F4);
  static const Color white = Color(0xFFFFFFFF);
  static const Color green = Color(0xFF17CF6B);
  static const Color greenShade900 = Color(0xFF027A48);
  static const Color greenShade50 = Color(0xFFECFDF3);
  static const Color greyShade100 = Color(0xFFECEDF0);
  static const Color greenShade200 = Color(0xFF4FBF67);
  static const Color textColor = Color(0xff575758);
  static const Color lighterText = Color(0xFF9D9D9D);
  static const Color appbarColor = Color(0xFFEEF2F6);
  static const Color tabBarColor = Color(0xFFF2F4F8);
  static const Color whiteShade80 = Color(0xFFF9F9F9);
  static const Color greyText = Color(0XFF555E67);
  static const Color greyTextShade100 = Color(0xFF9F9F9F);
  static const Color greyShade50 = Color(0xFFF5F5F5);
  static const Color dividerColor = Color(0xFFE8E6EA);
  static const Color lilac = Color(0xFFF8F8FF);
  static const Color textFieldBorder = Color(0xFF1B1D21);
  static const Color buttonBg = Color(0xFFFBFCFE);
  static const Color w5Color = Color(0xFF5A3D8B);
  static const Color lightPurple = Color(0xFFF3F0FF);
}
